### ISSUE TITLE
[Suggestion] Set custom %world% values

### ISSUE THREAD

**Issue by RaeTheGit** [hypherionmc/simple-rpc-public#13]
When e.g. in twilightforest dimension, %world% will resolve to the string "renderer"
I'd want the variable to actually represent the (human readable) name of the dimension.

It's probably not viable to get every dimension mod creator to supply a name in certain format that gets written into %world% by your mod, so my idea is to be able to configure human readable names for dimension IDs instead, which %world% will be set to, maybe in structure similar to [world_images] section.
The dimension IDs are usually easy to find out, or even configurable in the according mod.

If there already is a way to achieve this, I'd be happy to know and would suggest documenting it in the wiki so others can also easily find it.

Regards!

**Comment by hypherionmc** [comment]
Hi. I do believe this is a actually a bug and not a missing feature. The mod is supposed to pull the dimension name into %world% from the registry data of the game, which it obviously doesn't.

I noticed a similar issue with Pocket Dimensions 2, and I need to check later today to see why it's happening. I'm not sure if this happens with other dimensions as well, but atm it only seems to work properly with vanilla dimensions which causes me to be believe this a bug

**Comment by hypherionmc** [comment]
Okay so if you use forge 1.16, you can try out this build: https://ci.explodingcreeper.me/job/Simple%20RPC/job/Forge/job/1.16/15/artifact/build/libs/simple-rpc-1.16.5-dev-15-all.jar

Two things:

1) The mod will now try to automatically generate a display string for all dimensions (Since I found out MC doesn't actually have any display strings for dimensions....). So it will change for example atlantis:atlantis into Atlantis

2) The config has changed. You will notice that `world_images` has now become `dimension_overrides`. You don't need to change this, the mod will do it automatically.

Inside there, you can override the images, description and state based on what dimension you are in. `name` must be in the format as displayed when pressing F3. If you don't want to override a value, just leave it empty.

**Comment by RaeTheGit** [comment]
Sounds great! Will try to find time for testing tonight.

**Comment by RaeTheGit** [comment]
I can confirm it works. Nice!
Worth mentioning that it needs the exact dimension name, i.e. including mod prefix - that wasn't apparent to me when you mentioned the F3 screen.
And when started with OptiFine in the pack, this mod crashes on load with reference to a config file problem. I'm aware I'm potentially on my own as soon as I use OF together with mods. It still confused me a little as there were no visible conflicts with the old version.
I attached the crash log anyway in case you want to look into that. (I'm totally fine with the usual answer to this, though, that I then shouldn't use OF)

[crash-2021-07-29_07.18.58-fml.txt](https://github.com/hypherionmc/simple-rpc-public/files/6898267/crash-2021-07-29_07.18.58-fml.txt)

**Comment by hypherionmc** [comment]
Wait what huh... How even? The hell optifine??? The crashing line, is a line that just copies the discordID of the app into a temporary field.... 

Definitely a first for me, but I'll check it out. I've used both together before so it's strange

**Comment by hypherionmc** [comment]
Alright, can confirm that is indeed an issue. I've been able to replicate it multiple times. Will work on a fix for it, cause that isn't normal.

#14 - For reference

**Comment by hypherionmc** [comment]
This feature is now part of the 2.3 release
