### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by TheNPCFISH** [hypherionmc/simple-rpc-public#27]
Your way to edit rpc is too difficult. It would be easier if you just add [Mod Menu](https://www.curseforge.com/minecraft/mc-mods/modmenu) support because you can add there some settings. I hope you'll add it!

**Comment by hypherionmc** [comment]
Like Kaleidio said, we have an app dedicated to providing a Visual way to edit the config, with a built in preview. The discussion to add an in-game config system has popped up in the past, but maintaining such a system across both Fabric and Forge, as well as 1.12-1.18 is a nightmare, and would create a lot of work during porting work, that's why we went with an external system instead
