### ISSUE TITLE
Simple RPC (simple-rpc) encountered an error during the common_setup event phase java.lang.NullPointerException

### ISSUE THREAD

**Issue by dimti** [hypherionmc/simple-rpc-public#29]
```
Details:
	Mod File: simple-rpc-1.16.5-2.7.2.jar
	Failure message: Simple RPC (simple-rpc) encountered an error during the common_setup event phase
		java.lang.NullPointerException: null
	Mod Version: 2.7.2
	Mod Issue URL: https://github.com/hypherionmc/simple-rpc-public/issues
	Exception message: java.lang.NullPointerException
```

Crach log: https://file.slave.dimti.ru/share/rkkVuTvE

I downloaded this mod pack: https://www.curseforge.com/minecraft/modpacks/valhelsia-3

And launch fine on ArchLinux and Pop OS with nvidia cards.
But in other device based on intel notebook video - on java 1.8 in ubuntu 21 - some wrong.

**Comment by hypherionmc** [comment]
Hey. Thanks for the report. It looks like another mod was crashing first when trying to mixin to Minecraft (A mixin we don't make use of), and because of that, simple rpc failed to load directly after that and ending up being the mod blamed for the crash.

I'm not 100% sure, but looks like Create was the crashing mod just before that.

The graphics card in your system shouldn't have any effect on this mod, because it does nothing graphics related. It just passes information to discord
