### ISSUE TITLE
[BUG] Severe lag when playing on a server

### ISSUE THREAD

**Issue by squoshi** [hypherionmc/simple-rpc-public#51]
**Describe the bug**
Using Spark, I found out that every second, SDRPC causes _severe_ lag

**To Reproduce**
There aren't really any steps, but if you're doing a large modpack it causes the same issue.

**Expected behavior**
No lag

**Screenshots**
![image](https://user-images.githubusercontent.com/95097230/210199532-e8c9ce51-d594-4219-98ce-e45498ad6fd2.png)

**Versions (DO NOT USE LATEST! BE SPECIFIC!):**
 - OS: Windows 10
 - JAVA Version: 17
 - Mod Version: 3.2.0
 - Discord Version: Stable 165485 (07d8b41)
 - Minecraft Version: 1.18.2
 - Forge/Fabric Version: 40.1.92

**Comment by hypherionmc** [comment]
Okay so couple of questions here, the biggest one being, can you actually see the lag in your game? (Not on the profiler, but visually in the game)?

If yes, does the lag disappear with Simple RPC gone?

Reason I'm asking is, a while ago we had a huge drama moment with a then popular MC modpack, where it was reported that Simple RPC "lagged" the game, but no one could ever confirm that it causes visual FPS drops or lag.


The problem with using a profiler like Spark or even the Built in MC one, is that the % it shows, is how long a method is running combined with how often it's called. It's not actually reporting, "Hey, this thing inside this mod caused a lag spike for you", it's just saying, "Hey, this thing inside this mod is running a bit much".

The second is true for all reported methods of SRPC. ClientTick is called every tick, but it doesn't execute work every tick. Instead, it passed the info the mod needs to it internally, and then after a couple of seconds, the mod only does something with it.

So that's why I'm asking, can you visually see any lag caused by the mod? I am happy to look into this, but I just want to avoid the whole scenario we had last time

**Comment by squoshi** [comment]
Yes to both. It happens every second, it just freezes. It disappears when I disable it

**Comment by hypherionmc** [comment]
Hey. So I took a look at some of the recent changes we did, and I just have some follow up questions to help me determine if that is actually the problem.

1) Do you have any custom variables set up? If yes, how many?
2) Does the lag also occur in a single player game?
3) If no to 2, do you have simple rpc installed on your server as well, or only on the client?

**Comment by hypherionmc** [comment]
I'm suspecting the issue is with the server -> client config sync. If it is, the problem should be solved by removing the mod from the server

**Comment by Der-Fuzzi** [comment]
Yeah i'm also still having this issue, i'm playing on the newest version of the Prominence II [classic] 
A friend is hosting the world on Lan and only i am having the issue (when i'm hosting, only she is having the issue)

and funny thing, when i'm lagging, she can see me freeze in place... very weird

looking in the log file it consists of this:
![Unbenannt](https://github.com/hypherionmc/simple-rpc-public/assets/86323406/33e68920-5de8-4d65-98c1-0455aad0893e)

removing the mod has fixed the issue...
just wanted to let you know <3

**Comment by hypherionmc** [comment]
Interesting. I don't remember us using the profiler, BUT, it could be related to something else. Worth investigating.

Also worth mentioning that this mod has always been a problem for some users in LunaPixel modpacks (which is why the mod got removed from most of their packs in the first place). Never been able to figure out what causes it, and everyone's response was just to yeet the mod, and ignore any questions I had for debugging purposes.


I suspect however the issue from our side comes with the server config sync feature, which has been problematic and is scheduled for removal in a future release (probably by the 4.0.0 rewrite)

**Comment by hypherionmc** [comment]
I'm going to merge this issue with #88 as it's caused by the same piece of code. A craterlib update will be release in the next 2 days to address the issue, but this problem does span back several versions of Simple RPC. The real cause of it has been discovered recently. 

As far as well know, if only affects Direct connections and lan connections, but regardless, the piece of code is being removed with a dummy fallback
