### ISSUE TITLE
[Suggestion] Mod Compatibility for 1.8.9

### ISSUE THREAD

**Issue by qualk** [hypherionmc/simple-rpc-public#56]
**Is your feature request related to a problem? Please describe.**
I've used this brilliant mod with my other modpacks, but not my 1.8.9 PvP modpacks.

**Describe the solution you'd like**
I'd like to have support for 1.8.9.

**Describe alternatives you've considered**
Using a custom RPC client for Discord, but it wouldn't be able to know my current Minecraft state.

**Comment by hypherionmc** [comment]
As we mentioned to you on discord, back-porting this mod so far back will be a hell of a lot of work and I honestly don't remember much about modding below 1.16.5 at this point.

Even if it was backported, it would never be officially released anywhere, since I don't develop for versions older than 1.16.5 because of time constraints and my personal life getting in the way.

You are welcome to try out the new CraftPresence beta's, which even include a built in migration system for Simple RPC configs.
