### ISSUE TITLE
1.19.4 load error 

### ISSUE THREAD

**Issue by forditt** [hypherionmc/simple-rpc-public#57]
The game won't load

![зображення](https://user-images.githubusercontent.com/105544922/226109689-af57445b-a3d1-4422-8c47-0bbb665ee7ef.png)

 - OS: Windows 11 22H2
 - JAVA Version: 17?
 - Mod Version: simple-rpc-fabric-1.19.x-3.2.1
 - Discord Version: 🤨
 - Minecraft Version: 1.19.4
 - Forge/Fabric Version: 0.14.17

**Comment by hypherionmc** [comment]
1.19.4 was only released this week, and the mod has not yet been tested or updated to support it. That's why it's not marked as 1.19.4 supported on Curseforge and Modrinth.

I'm still busy updating mods as they require it, so there will likely only be a release late today or tomorrow that supports it

**Comment by forditt** [comment]
Got it, thanks for the reply

**Comment by hypherionmc** [comment]
A version supporting 1.19.4 has been released on Curse and Modrinth

**Comment by forditt** [comment]
thank you
