### ISSUE TITLE
[Suggestion] ModMenu Config

### ISSUE THREAD

**Issue by barraIhsan** [hypherionmc/simple-rpc-public#60]
**Is your feature request related to a problem? Please describe.**
So you can config them inside the game using ModMenu (fabric)

**Describe the solution you'd like**
Integrate it, so that you can click the config icon when opening the modmenu
![image](https://github.com/hypherionmc/simple-rpc-public/assets/57800056/2bb279ec-c3f3-4034-9097-df00d7037a9c)

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by hypherionmc** [comment]
While we don't support ModMenu yet, the 1.20+ versions will. On every other version, if you have Cloth Config installed, a "Discord" button will appear at the top right of the options screen, that opens a config gui. Please note that the in-game GUI is nowhere near as complete as the standalone config editor, since Mojang keeps breaking it, and I pretty much gave up on trying to maintain it

**Comment by hypherionmc** [comment]
A long time has passed since this issue, and our in game config screen has been discontinued for most part, because it doesn't get the love it deserves and has always been far behind our editor.

We have since launched a new online editor at https://editor.firstdark.dev so you no longer need to download an external app.

Going to close this for now for housekeeping so that we can focus on Version 4 :)
