### ISSUE TITLE
Log spammed with RichPresence text

### ISSUE THREAD

**Issue by benbenlaw** [hypherionmc/simple-rpc-public#8]
**Describe the bug**
I was looking at my debug long and saw it was absolutly spammed with various discord api checking, sometimes twice a second. Also getting random freezes from normal fps is 200+ and randomly drops down to 0
**To Reproduce**
1. insall
2. watch debug log

**Expected behavior**
no freezes and not as many checks
**Screenshots**
![image](https://user-images.githubusercontent.com/42780877/117422320-60ea2b80-af17-11eb-9f9f-a824e8db675d.png)

**Versions (DO NOT USE LATEST! BE SPECIFIC!):**
 - OS: windows
 - JAVA Version: 8
 - Mod Version: 2.1.1
 - Discord Version: not sure
 - Minecraft Version: 1.16.5
 - Forge Version: 36.1.16
 
**Additional context**

**Comment by hypherionmc** [comment]
Hi

Firstly, thanks so much for actually reporting this and not just keeping quiet.

So the log spam you are noticing is actually the discord API itself and not the mod, however, I can do something about it.

I am just curious, you don't happen to have an AMD cpu by any chance?

**Comment by benbenlaw** [comment]
yeah amd, im talking to a few people on my modpack discord and a few on them are having this issue

**Comment by benbenlaw** [comment]
so that amount of debug text is normal?

**Comment by hypherionmc** [comment]
My god thank you for finally giving me useful information!! People have been reporting lag on AMD for a while, but no one actually gave me logs or anything useful so that I could track down the issue.

No that is not normal at all, but, for some reason, the issue seems to be isolated to AMD systems. I have no idea why, but I haven't had any complaints from intel users.

I will do the fix this weekend, would you mind testing it for me before I release it?

**Comment by benbenlaw** [comment]
yeah no worries can i add you on discord ? i dont always see github logs

**Comment by hypherionmc** [comment]
I answered you on discord :)

**Comment by hypherionmc** [comment]
Issue has been fixed
