### ISSUE TITLE
[Suggestion] Don't leak a servers IP by default / ingame full configuration gui

### ISSUE THREAD

**Issue by Sanduhr32** [hypherionmc/simple-rpc-public#9]
**Is your feature request related to a problem? Please describe.**
My server is protected, but this is just annoying.
Over 100k ppl can see my servers ip because i'm well known / staff in some community servers.
Give me privacy by default.

**Describe the solution you'd like**
Don't include the server ip in format string in the default json config for servers

**Describe alternatives you've considered**
Add an ingame GUI for configuring what the RPC will display.

**Additional context**
Dude it's 2021 not 1980s, privacy is a big deal imo, github had a 1.3 Tb/s ddos in march 2018.
Do you think the future will have less & smaller attacks?

**Comment by hypherionmc** [comment]
My apologies if it made you feel that way, but that was a requested feature so that's why it's included. You can always just remove the %ip% variable from the config

As for the GUI, I did consider it, and was partly implemented, but it got too complicated to maintain it across all versions and modloaders. I am working on a utility to handle editing config files with an interface

**Comment by Sanduhr32** [comment]
#10 is probably a good reference to link probably.

**Comment by hypherionmc** [comment]
Fixed in 2.2 and a config editor utility is now available
