### ISSUE TITLE
Optimizing Discord Bot Response Time

### ISSUE THREAD

**Issue by linty1997** [hypherionmc/simple-rpc-public#95]
Issue Description: Our server is located within China, while our users are overseas. Due to the unique internet environment in China, accessing Discord results in significant delays. When executing commands with the Discord bot, we often encounter timeouts. We are looking for solutions to enhance the bot's tolerance for network latency.

Possible Solution: We inquire whether it's possible to incorporate a longer waiting mechanism into the bot's code, similar to the ctx.defer() and send_followup methods in Python, allowing the bot more time to wait and process commands, thus avoiding timeouts due to prolonged response times. We hope to find a similar implementation in a Java environment or address the impact of network delays through other technical means.

**Comment by hypherionmc** [comment]
Wrong repo.

That being said, we already utilize all the utilities provided by discord to ensure commands can take longer to run, and that the bot has a longer time to respond to messages/commands.

So if you are still having timeout issues, there is not really much more we can do from our side. Discord still has hard limits no matter what.

What areas specifically are you having issues with?

**Comment by linty1997** [comment]
For instance, when linking users using commands, I experience issues where the request remains unresponded. In fact, it’s not just the verification command; all commands face this issue of ‘unresponded requests’. However, the wait isn't too long, typically around five seconds. ERROR RestAction - RestAction queue returned failure: [ErrorResponseException] 10062: Unknown interaction

**Comment by hypherionmc** [comment]
See, we already use [Deferred](https://github.com/hypherionmc/sdlink/blob/aeceb62778ac9375cbf72366bb5b7b39dad93d49/src/main/java/com/hypherionmc/sdlink/core/discord/commands/slash/verification/VerifyAccountCommand.java#L33) replies for the verification commands.

What I suspect what's happening here, is because of the extreme latency between your server and discord, by the time the command actually reaches your server for the bot to process/defer etc, it already timed out.

Discord expects bots to acknowledge commands in less than 3 seconds (even if you defer the reply, the bot has to tell discord that is got the command and is busy with it in less than 3 seconds), so if the command takes 4-5 seconds to reach the bot, the command is already timed out and invalid.

So this is really a discord issue, and not an issue with us. The only way you will really solve it is to get your latency down so the command reaches your server from discord faster

**Comment by linty1997** [comment]
Alright, I understand. Thank you very much for your response.
